name: Build and deploy the simple vite version
on:
  push:
    branches:
      - simple-vite-version
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          ref: simple-vite-version
      
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install and Build ðŸ”§
        run: |
          yarn install
          yarn tail-build-prod
          yarn build
      
      - name: Add custom domain to CNAME file
        run: echo "steekam.me" > CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
